services:
    wizarr:
        build: .
        ports:
            - 5690:5690
        volumes:
            - ./test-data:/data/database
        environment:
            - TZ=Europe/London
            - PGID=1000000
            - PUID=1000000
            - UV_CACHE_DIR=/.cache/uv
            #- WIZARR_API_KEY= # Optional: uncomment and create your own key to enable /api/status endpoint